// <auto-generated />
using System;
using Imortais.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imortais.Migrations
{
    [DbContext(typeof(ImortaisContext))]
    partial class ImortaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Imortais.Models.Elenco", b =>
                {
                    b.Property<int>("elencoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("assistencias");

                    b.Property<int>("ativo");

                    b.Property<int>("ca");

                    b.Property<int>("cv");

                    b.Property<DateTime>("dtContratacao");

                    b.Property<int>("gols");

                    b.Property<string>("img")
                        .IsRequired();

                    b.Property<string>("nome")
                        .IsRequired();

                    b.Property<string>("posicao")
                        .IsRequired();

                    b.HasKey("elencoId");

                    b.ToTable("elenco");
                });

            modelBuilder.Entity("Imortais.Models.EventoImortais", b =>
                {
                    b.Property<int>("EventoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEvento");

                    b.Property<string>("DescricaoEvento");

                    b.HasKey("EventoID");

                    b.ToTable("eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
